---
- hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Install necessary packages
      yum: name={{ item }} state=present update_cache=yes
      with_items:
        - epel-release
        - git
        - python
        - python-devel
        - python-pip
