---
- hosts: localhost
  connection: local
  become: yes

  vars:
    user_name: ansible
    user_pwd: $1$SomeSalt$LRZdP3TwZZZ/q8adbdC0g0
    user_group: wheel

  tasks:
    - name: Make sure we have a 'wheel' group
      group: name={{ user_group }} state=present

    - name: Allow '{{ user_name }}' to have passwordless sudo
      lineinfile: 
        dest: /etc/sudoers 
        state: present
        regexp: '^{{user_name}}'
        line: '{{user_name}} ALL=(ALL) NOPASSWD: ALL'

    - name: Create new user
      user: name={{ user_name }} group={{ user_group }} 
